name: GitHub Actions Demo
on: [push]
jobs:
  Prettier:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
      - run: yarn install
      - name: Prettier
